[[repo]]
path = "github/django/.github"
url = "git@github.com:django/.github.git"
branch = "main"

[[repo]]
path = "github/django/asgiref"
url = "git@github.com:django/asgiref.git"
branch = "main"

[[repo]]
path = "github/django/channels"
url = "git@github.com:django/channels.git"
branch = "main"

[[repo]]
path = "github/django/channels_redis"
url = "git@github.com:django/channels_redis.git"
branch = "main"

[[repo]]
path = "github/django/code-of-conduct"
url = "git@github.com:django/code-of-conduct.git"
branch = "main"

[[repo]]
path = "github/django/code.djangoproject.com"
url = "git@github.com:django/code.djangoproject.com.git"
branch = "main"

[[repo]]
path = "github/django/daphne"
url = "git@github.com:django/daphne.git"
branch = "main"

[[repo]]
path = "github/django/deps"
url = "git@github.com:django/deps.git"
branch = "main"

[[repo]]
path = "github/django/django"
url = "git@github.com:django/django.git"
branch = "main"

[[repo]]
path = "github/django/django-asv"
url = "git@github.com:django/django-asv.git"
branch = "main"

[[repo]]
path = "github/django/django-contrib-comments"
url = "git@github.com:django/django-contrib-comments.git"
branch = "master"

[[repo]]
path = "github/django/django-docker-box"
url = "git@github.com:django/django-docker-box.git"
upstream = "git@github.com:orf/django-docker-box.git"
branch = "main"

[[repo]]
path = "github/django/django-docs-translations"
url = "git@github.com:django/django-docs-translations.git"
branch = "main"

[[repo]]
path = "github/django/django-fuzzers"
url = "git@github.com:django/django-fuzzers.git"
branch = "master"

[[repo]]
path = "github/django/django-localflavor"
url = "git@github.com:django/django-localflavor.git"
branch = "master"

[[repo]]
path = "github/django/djangoproject.com"
url = "git@github.com:django/djangoproject.com.git"
branch = "main"

[[repo]]
path = "github/django/djangosnippets.org"
url = "git@github.com:django/djangosnippets.org.git"
branch = "main"

[[repo]]
path = "github/django/ticketbot"
url = "git@github.com:django/ticketbot.git"
branch = "main"

[[repo]]
path = "gitlab/tom6/backend-coding-challenge"
url = "git@gitlab.com:tom6/backend-coding-challenge.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/jiri-gitlab"
url = "git@gitlab.com:tom6/jiri-gitlab.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/metrics-bug"
url = "git@gitlab.com:tom6/metrics-bug.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/minimal-ruby-app"
url = "git@gitlab.com:tom6/minimal-ruby-app.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/resizer"
url = "git@gitlab.com:tom6/resizer.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/test-empty-project"
url = "git@gitlab.com:tom6/test-empty-project.git"

[[repo]]
path = "gitlab/tom6/test-lfs"
url = "git@gitlab.com:tom6/test-lfs.git"
branch = "master"
